enable-blacklist: True
default-item-distribution: "2,6,9,6,2"
default-num-lines-complete-for-win: 1
show-currently-winning-team: True
prevent-water-spawns: True
show-all-maps-after-game: True
border:
  enable: True
  overworld-size: 3000
  nether-size: 1000
timer:
  enable: True
  length: 1800
pregeneration-mode:
  enable: False
  ticks-per-cycle: 100
  chunks-per-cycle: 200
